# custom
alias alias.edit='nvim ~/.bash_aliases'
alias alias.find='alias | grep $1'
alias apt.installed='apt list --installed'
alias apt.installed.find='apt list --installed | grep $1'
# alias dev='cd /media/sf_Development ; clear'
alias shell.set.zsh='chsh -s $(which zsh)'
alias shell.set.bash='chsh -s $(which bash)'
# alias work='cd ~/Workspaces ; clear'
alias zsh.config='nvim ~/.zshrc'

# common
alias cd.='cd .'
alias cd..='cd ..'
alias clr='clear'
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias lsa='ls -lah'
alias rd='rm -r'
alias rdf!='rm -fr'
alias rmdir='rm -r'
alias rst='reset'
alias zsdir='du -h --max-depth=1'
alias zd='zsdir'

# elementary os
# alias code='io.elementary.code'

# nvim
alias v='nvim .'
alias vim.config='nvim ~/.config/vim/'

# node packages
alias ni='npm install'
alias nig='sudo npm instal --global'
alias nu='npm uninstall'
alias pa='pnpm add'
alias pad='pnpm add --save-dev'
alias pi='pnpm install'
alias pls='pnpm list'
alias po='pnpm outdated'
alias pr='pnpm remove'
alias pu='pnpm update'
alias ya='yarn add'
alias yad='yarn add --save-dev'
alias yd='yarn dev'
alias yga='sudo yarn global add'
alias ygl='sudo yarn global list'
alias ygr='sudo yarn global remove'
alias ygu='sudo yarn global upgrade'
alias yi='yarn init'
alias yl='yarn lint'
alias ylf='yarn lint --fix'
alias yls='yarn list'
alias yp='yarn publish'
alias ypp='yarn publish --access public'
alias yr='yarn remove'
alias yt='yarn test'
alias yu='yarn upgrade'

# laravel
alias art='php artisan'
alias pabb='php artisan blueprint:build'
alias pabe='php artisan blueprint:erase'
alias pabn='php artisan blueprint:new'

#docker
alias dattach='docker attach'
alias dbuild='docker build'
alias dbuilder='docker builder'
alias dcommit='docker commit'
alias dconfig='docker config'
alias dcontainer='docker container'
alias dcls='docker container ls'
alias dcprune='docker container prune'
alias dcrm='docker container rm'
alias dcrmf!='docker container rm --force'
alias dcontext='docker context'
alias dcp='docker cp'
alias dcreate='docker create'
alias ddiff='docker diff'
alias devents='docker events'
alias dexec='docker exec'
alias dexport='docker export'
alias dhistory='docker history'
alias dimage='docker image'
alias dib='docker image build'
alias dibf='docker image build --file'
alias dibt='docker image build --tag'
alias dils='docker image ls'
alias diprune='docker image prune'
alias dirm='docker image rm'
alias dirmf!='docker image rm --force'
alias dimages='docker images'
alias dimport='docker import'
alias dinfo='docker info'
alias dinspect='docker inspect'
alias dkill='docker kill'
alias dload='docker load'
alias dlogin='docker login'
alias dlogout='docker logout'
alias dlogs='docker logs'
alias dmanifest='docker manifest'
alias dnetwork='docker network'
alias dnct='docker network connect'
alias dnc='docker network create'
alias dndt='docker network disconnect'
alias dni='docker network inspect'
alias dnls='docker network ls'
alias dnprune='docker network prune'
alias dnrm='docker network rm'
alias dnrmf!='docker network rm --force'
alias dnode='docker node'
alias dpause='docker pause'
alias dplugin='docker plugin'
alias dport='docker port'
alias dprune='dcprune -f ; diprune -f ; dvprune -f'
alias dps='docker ps'
alias dpsaa='docker ps --all'
alias dpsid='docker ps --quiet'
alias dpsidaa='docker ps --quiet --all'
alias dpull='docker pull'
alias dpush='docker push'
alias drename='docker rename'
alias drestart='docker restart'
alias drm='docker rm'
alias drmi='docker rmi'
alias drun='docker run'
alias dsave='docker save'
alias dscan='docker scan'
alias dsearch='docker search'
alias dsecret='docker secret'
alias dservice='docker service'
alias dstack='docker stack'
alias dstart='docker start'
alias dstats='docker stats'
alias dstop='docker stop'
alias dswarm='docker swarm'
alias dsystem='docker system'
alias dtag='docker tag'
alias dtop='docker top'
alias dtrust='docker trust'
alias dunpause='docker unpause'
alias dupdate='docker update'
alias dversion='docker version'
alias dvolume='docker volume'
alias dvc='docker volume create'
alias dvi='docker volume inspect'
alias dvls='docker volume ls'
alias dvprune='docker volume prune'
alias dvrm='docker volume rm'
alias dvrmf!='docker volume rm --force'
alias dwait='docker wait'
